name: easynetqtest

services:
  easynetqtest:
    image: easynetq/easynetqtest:latest
    container_name: easynetqtest
    build:
      context: ../src
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+80
      - ConnectionStrings__rabbitmq=host=rabbitmq;virtualHost=/;username=guest;password=guest;timeout=60;publisherConfirms=True
    depends_on:
      rabbitmq:
        condition: service_healthy

  rabbitmq:
    image: rabbitmq:3-management
    container_name: easynetqtest_rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
        test: [ "CMD", "rabbitmqctl", "status" ]
        interval: 3s
        timeout: 5s
        retries: 10
        start_period: 5s